/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /auth/logout. */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/phone/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /auth/phone/request — отправить код по SMS. Доступ: все. */
        post: operations["auth_phone_request_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/phone/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /auth/phone/verify — проверить код, создать сессию. Доступ: все. */
        post: operations["auth_phone_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /blocks */
        post: operations["blocks_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blocks/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description DELETE /blocks/{userId} */
        delete: operations["blocks_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gatherings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Лента сборов
         * @description GET /gatherings — лента; POST /gatherings — создать сбор.
         */
        get: operations["gatherings_list"];
        put?: never;
        /**
         * Создать сбор
         * @description GET /gatherings — лента; POST /gatherings — создать сбор.
         */
        post: operations["gatherings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gatherings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Сбор целиком
         * @description GET /gatherings/{id}; PATCH — только создатель.
         */
        get: operations["gatherings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Изменить время, место, комментарий (создатель)
         * @description GET /gatherings/{id}; PATCH — только создатель.
         */
        patch: operations["gatherings_partial_update"];
        trace?: never;
    };
    "/api/v1/gatherings/{id}/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** «Я пришёл» (участник, от начала до +12 ч) */
        post: operations["gatherings_attendance_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gatherings/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отменить с причиной (создатель) */
        post: operations["gatherings_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gatherings/{id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Присоединиться */
        post: operations["gatherings_join_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gatherings/{id}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Выйти */
        post: operations["gatherings_leave_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gatherings/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * История чата (новые сверху)
         * @description GET /gatherings/{id}/messages — история; POST — отправка. Только участник.
         */
        get: operations["gatherings_messages_list"];
        put?: never;
        /**
         * Отправить сообщение
         * @description GET /gatherings/{id}/messages — история; POST — отправка. Только участник.
         */
        post: operations["gatherings_messages_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gatherings/{id}/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Оценить участников (участник, до +48 ч) */
        post: operations["gatherings_ratings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /health — проверка после выкладки и внешний мониторинг.
         *     503, если БД или Redis недоступны.
         */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Свой профиль
         * @description GET /me, PATCH /me (онбординг), DELETE /me (удаление аккаунта).
         */
        get: operations["me_retrieve"];
        put?: never;
        post?: never;
        /** @description GET /me, PATCH /me (онбординг), DELETE /me (удаление аккаунта). */
        delete: operations["me_destroy"];
        options?: never;
        head?: never;
        /** @description GET /me, PATCH /me (онбординг), DELETE /me (удаление аккаунта). */
        patch: operations["me_partial_update"];
        trace?: never;
    };
    "/api/v1/me/gatherings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Мои сборы
         * @description GET /me/gatherings?when=upcoming|past
         */
        get: operations["me_gatherings_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/notifications/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET/PATCH /me/notifications/settings */
        get: operations["me_notifications_settings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description GET/PATCH /me/notifications/settings */
        patch: operations["me_notifications_settings_partial_update"];
        trace?: never;
    };
    "/api/v1/me/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /me/photo — до 5 МБ, JPG/PNG/WebP. */
        post: operations["me_photo_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/push-subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /me/push-subscriptions */
        post: operations["me_push_subscriptions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/places/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /places/search?q= — прокси к 2ГИС. */
        get: operations["places_search_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/public/gatherings/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Сбор по ссылке без личных данных
         * @description Без входа: для SSR страницы /g/<slug> и превью в мессенджерах.
         */
        get: operations["public_gatherings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /reports */
        post: operations["reports_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/telegram/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /telegram/link — вернуть ссылку t.me/<bot>?start=<token>. */
        post: operations["telegram_link_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/telegram/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /telegram/webhook — проверка X-Telegram-Bot-Api-Secret-Token. */
        post: operations["telegram_webhook_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /users/{id} — публичный профиль. */
        get: operations["users_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {unknown} */
        BlankEnum: "";
        CancelRequest: {
            reason: string;
        };
        Category: {
            /** Код */
            slug: string;
            /** Название */
            name: string;
            /** Эмодзи */
            emoji?: string;
        };
        /** @description Место из поиска 2ГИС: координаты приходят отдельными полями, в БД — PointField. */
        GatheringCreateRequest: {
            /** Код */
            category: string;
            /** Название */
            title: string;
            /** Комментарий */
            comment?: string;
            /** Название места */
            place_name: string;
            /** Адрес */
            address: string;
            /** Район */
            district?: string;
            /** Id места в 2ГИС */
            place_external_id: string;
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
            /**
             * Начало
             * Format: date-time
             */
            starts_at: string;
            seats: number;
        };
        /** @description Сбор целиком: точный адрес, координаты, участники. */
        GatheringDetail: {
            readonly id: number;
            readonly slug: string;
            /** Название */
            title: string;
            category: components["schemas"]["Category"];
            /**
             * Начало
             * Format: date-time
             */
            starts_at: string;
            /** Название места */
            place_name: string;
            /** Район */
            district?: string;
            /** Мест всего */
            seats: number;
            participants_count: number;
            /** Статус */
            status?: components["schemas"]["StatusEnum"];
            /** @default false */
            is_participant: boolean;
            /**
             * Format: double
             * @description если в запросе были lat/lng
             */
            distance_m?: number | null;
            /** Комментарий */
            comment?: string;
            /** Адрес */
            address: string;
            /** Id места в 2ГИС */
            place_external_id: string;
            /** Format: double */
            readonly lat: number;
            /** Format: double */
            readonly lng: number;
            creator: components["schemas"]["UserShort"];
            readonly is_creator: boolean;
            readonly participants: components["schemas"]["Participant"][];
            /** Модерация */
            moderation_status?: components["schemas"]["ModerationStatusEnum"];
            /** Причина отмены */
            cancel_reason?: string;
            /**
             * Отменён
             * Format: date-time
             */
            cancelled_at?: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        /** @description Карточка ленты. */
        GatheringList: {
            readonly id: number;
            readonly slug: string;
            /** Название */
            title: string;
            category: components["schemas"]["Category"];
            /**
             * Начало
             * Format: date-time
             */
            starts_at: string;
            /** Название места */
            place_name: string;
            /** Район */
            district?: string;
            /** Мест всего */
            seats: number;
            participants_count: number;
            /** Статус */
            status?: components["schemas"]["StatusEnum"];
            /** @default false */
            is_participant: boolean;
            /**
             * Format: double
             * @description если в запросе были lat/lng
             */
            distance_m?: number | null;
        };
        /** @description Для страницы /g/<slug> гостю и Open Graph: без имён, фото и точного адреса. */
        GatheringPublic: {
            readonly id: number;
            readonly slug: string;
            /** Название */
            title: string;
            category: components["schemas"]["Category"];
            /**
             * Начало
             * Format: date-time
             */
            starts_at: string;
            /** Район */
            district?: string;
            /** Мест всего */
            seats: number;
            participants_count: number;
            /** Статус */
            status?: components["schemas"]["StatusEnum"];
        };
        /**
         * @description * `user` - Сообщение участника
         *     * `system` - Системное
         * @enum {string}
         */
        KindEnum: "user" | "system";
        /**
         * @description Свой профиль: телефон виден только самому пользователю.
         *     TODO: запись (онбординг: 18+, согласия, имя, вуз, интересы) — вместе с входом по телефону.
         */
        Me: {
            readonly id: number;
            /** Телефон */
            readonly phone: string;
            /** Имя */
            readonly name: string;
            /**
             * Фото
             * Format: uri
             */
            readonly photo: string | null;
            university?: string;
            /** Роль */
            readonly role: components["schemas"]["RoleEnum"];
            /**
             * Надёжность
             * Format: double
             */
            readonly reliability: number | null;
            /** Состоявшихся сборов */
            readonly happened_gatherings_count: number;
            readonly onboarding_completed: boolean;
        };
        /** @description Сообщение в истории и в событии message.new. Скрытое — без текста и данных. */
        Message: {
            readonly id: number;
            gathering: number;
            /** Тип */
            kind?: components["schemas"]["KindEnum"];
            /** Событие */
            system_event?: components["schemas"]["SystemEventEnum"] | components["schemas"]["BlankEnum"];
            author: components["schemas"]["UserShort"] | null;
            readonly text: string;
            readonly payload: {
                [key: string]: unknown;
            };
            /** Скрыто модератором */
            is_hidden?: boolean;
            /**
             * Отправлено
             * Format: date-time
             */
            readonly created_at: string;
        };
        MessageCreateRequest: {
            text: string;
        };
        /**
         * @description * `published` - Опубликован
         *     * `pending` - На проверке
         *     * `hidden` - Скрыт модератором
         * @enum {string}
         */
        ModerationStatusEnum: "published" | "pending" | "hidden";
        PaginatedGatheringListList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["GatheringList"][];
        };
        PaginatedMessageList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Message"][];
        };
        Participant: {
            user: components["schemas"]["UserShort"];
            is_creator: boolean;
            /** Format: date-time */
            joined_at: string;
        };
        /** @description Изменить можно время, место, комментарий. Место меняется целиком. */
        PatchedGatheringUpdateRequest: {
            /**
             * Начало
             * Format: date-time
             */
            starts_at?: string;
            /** Комментарий */
            comment?: string;
            /** Название места */
            place_name?: string;
            /** Адрес */
            address?: string;
            /** Район */
            district?: string;
            /** Id места в 2ГИС */
            place_external_id?: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
        };
        RatingItemRequest: {
            user_id: number;
            value: components["schemas"]["ValueEnum"];
        };
        RatingsRequest: {
            ratings: components["schemas"]["RatingItemRequest"][];
        };
        /**
         * @description * `user` - Пользователь
         *     * `moderator` - Модератор
         *     * `admin` - Администратор
         * @enum {string}
         */
        RoleEnum: "user" | "moderator" | "admin";
        /**
         * @description * `open` - Набор открыт
         *     * `full` - Мест нет
         *     * `cancelled` - Отменён
         *     * `finished` - Прошёл
         * @enum {string}
         */
        StatusEnum: "open" | "full" | "cancelled" | "finished";
        /**
         * @description * `joined` - Присоединился
         *     * `left` - Вышел
         *     * `updated` - Сбор изменён
         *     * `cancelled` - Сбор отменён
         *     * `creator_changed` - Сменился создатель
         * @enum {string}
         */
        SystemEventEnum: "joined" | "left" | "updated" | "cancelled" | "creator_changed";
        /** @description Участник в сборе: имя, фото, вуз. Телефон не отдаём никогда. */
        UserShort: {
            readonly id: number;
            /** Имя */
            name?: string;
            /**
             * Фото
             * Format: uri
             */
            photo?: string | null;
            university?: string;
        };
        /**
         * @description * `ok` - Пришёл, всё хорошо
         *     * `no_show` - Не пришёл
         * @enum {string}
         */
        ValueEnum: "ok" | "no_show";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_phone_request_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_phone_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    blocks_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    blocks_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    gatherings_list: {
        parameters: {
            query?: {
                /** @description slug категории */
                category?: string;
                /** @description The pagination cursor value. */
                cursor?: string;
                /**
                 * @description по календарю Алматы
                 *
                 *     * `today` - today
                 *     * `tomorrow` - tomorrow
                 *     * `week` - week
                 */
                date?: "today" | "tomorrow" | "week";
                lat?: number;
                lng?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedGatheringListList"];
                };
            };
        };
    };
    gatherings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GatheringCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["GatheringCreateRequest"];
                "multipart/form-data": components["schemas"]["GatheringCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatheringDetail"];
                };
            };
        };
    };
    gatherings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatheringDetail"];
                };
            };
        };
    };
    gatherings_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedGatheringUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedGatheringUpdateRequest"];
                "multipart/form-data": components["schemas"]["PatchedGatheringUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatheringDetail"];
                };
            };
        };
    };
    gatherings_attendance_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Отмечено */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    gatherings_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CancelRequest"];
                "multipart/form-data": components["schemas"]["CancelRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatheringDetail"];
                };
            };
        };
    };
    gatherings_join_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatheringDetail"];
                };
            };
        };
    };
    gatherings_leave_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatheringDetail"];
                };
            };
        };
    };
    gatherings_messages_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMessageList"];
                };
            };
        };
    };
    gatherings_messages_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MessageCreateRequest"];
                "multipart/form-data": components["schemas"]["MessageCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    gatherings_ratings_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatingsRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RatingsRequest"];
                "multipart/form-data": components["schemas"]["RatingsRequest"];
            };
        };
        responses: {
            /** @description Сохранено */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    me_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_gatherings_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /**
                 * @description * `upcoming` - upcoming
                 *     * `past` - past
                 */
                when?: "upcoming" | "past";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedGatheringListList"];
                };
            };
        };
    };
    me_notifications_settings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_notifications_settings_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_photo_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_push_subscriptions_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    places_search_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    public_gatherings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatheringPublic"];
                };
            };
        };
    };
    reports_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "ru";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    telegram_link_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    telegram_webhook_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
