# Generated by Django 5.2.17 on 2026-10-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='название')),
                ('short_name', models.CharField(db_comment='для профиля, например Narxoz, КБТУ', max_length=30, verbose_name='короткое имя')),
                ('city', models.CharField(default='Алматы', max_length=50, verbose_name='город')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
            ],
            options={
                'verbose_name': 'вуз',
                'verbose_name_plural': 'вузы',
                'db_table_comment': 'Справочник вузов для необязательного поля профиля',
                'ordering': ['sort_order', 'short_name'],
            },
        ),
    ]
