# Generated by Django 5.2.17 on 2026-10-05 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notification_settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('joined_left', models.BooleanField(db_comment='только создателю', default=True, verbose_name='кто-то присоединился / вышел')),
                ('chat_message', models.BooleanField(db_comment='не чаще 1 раза в 10 минут', default=True, verbose_name='новое сообщение в чате')),
                ('reminder', models.BooleanField(default=True, verbose_name='напоминание за 2 часа')),
                ('updated', models.BooleanField(default=True, verbose_name='сбор изменён')),
                ('after_prompt', models.BooleanField(default=True, verbose_name='«Как прошла встреча?»')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
            ],
            options={
                'verbose_name': 'настройки уведомлений',
                'verbose_name_plural': 'настройки уведомлений',
                'db_table_comment': 'Переключатели уведомлений по типам (отмена — всегда включена)',
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('webpush', 'Web Push'), ('apns', 'APNs (iOS)'), ('fcm', 'FCM (Android)')], default='webpush', max_length=16, verbose_name='тип')),
                ('endpoint', models.TextField(db_comment='URL Web Push или токен устройства', unique=True, verbose_name='endpoint / токен')),
                ('keys', models.JSONField(blank=True, db_comment='p256dh и auth для Web Push', default=dict, verbose_name='ключи')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='устройство')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='последняя отправка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'подписка на пуши',
                'verbose_name_plural': 'подписки на пуши',
                'db_table_comment': 'Подписки Web Push (потом APNs/FCM)',
            },
        ),
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_token', models.CharField(blank=True, db_comment='одноразовый, обнуляется после привязки', max_length=64, null=True, unique=True, verbose_name='токен диплинка')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='chat_id')),
                ('linked_at', models.DateTimeField(blank=True, null=True, verbose_name='привязан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'привязка Telegram',
                'verbose_name_plural': 'привязки Telegram',
                'db_table_comment': 'Привязка аккаунта к Telegram-боту уведомлений',
            },
        ),
    ]
