# Generated by Django 5.2.17 on 2026-10-05 11:21

import apps.gatherings.slugs
import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gathering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(db_comment='ссылка /g/<slug>', default=apps.gatherings.slugs.generate_slug, max_length=16, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=60, verbose_name='название')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='комментарий')),
                ('place_name', models.CharField(max_length=200, verbose_name='название места')),
                ('address', models.CharField(db_comment='точный адрес — только участникам', max_length=300, verbose_name='адрес')),
                ('district', models.CharField(blank=True, db_comment='показывается гостям вместо адреса', max_length=100, verbose_name='район')),
                ('place_external_id', models.CharField(db_comment='адрес выбран из поиска, не свободный ввод', max_length=64, verbose_name='id места в 2ГИС')),
                ('location', django.contrib.gis.db.models.fields.PointField(db_comment='для сортировки ленты по расстоянию', geography=True, srid=4326, verbose_name='координаты')),
                ('starts_at', models.DateTimeField(db_comment='UTC; создание — от +1 ч до +14 дней', verbose_name='начало')),
                ('seats', models.PositiveSmallIntegerField(db_comment='3–6, включая создателя', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(6)], verbose_name='мест всего')),
                ('status', models.CharField(choices=[('open', 'Набор открыт'), ('full', 'Мест нет'), ('cancelled', 'Отменён'), ('finished', 'Прошёл')], default='open', max_length=16, verbose_name='статус')),
                ('moderation_status', models.CharField(choices=[('published', 'Опубликован'), ('pending', 'На проверке'), ('hidden', 'Скрыт модератором')], db_comment='pending — сработал фильтр запрещённых слов', default='published', max_length=16, verbose_name='модерация')),
                ('cancel_reason', models.CharField(blank=True, max_length=300, verbose_name='причина отмены')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='отменён')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gatherings', to='catalog.category', verbose_name='категория')),
                ('creator', models.ForeignKey(db_comment='текущий создатель — роль может передаваться другому участнику', on_delete=django.db.models.deletion.PROTECT, related_name='created_gatherings', to=settings.AUTH_USER_MODEL, verbose_name='создатель')),
            ],
            options={
                'verbose_name': 'сбор',
                'verbose_name_plural': 'сборы',
                'db_table_comment': 'Сборы: что, где, когда, сколько мест',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_creator', models.BooleanField(default=False, verbose_name='создатель')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='присоединился')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='вышел')),
                ('late_leave', models.BooleanField(db_comment='вышел менее чем за 2 ч до начала — снижает надёжность', default=False, verbose_name='поздний выход')),
                ('gathering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='gatherings.gathering')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'участие',
                'verbose_name_plural': 'участия',
                'db_table_comment': 'Участники сборов; left_at IS NULL — сейчас в сборе',
            },
        ),
        migrations.AddField(
            model_name='gathering',
            name='participants',
            field=models.ManyToManyField(related_name='gatherings', through='gatherings.Participation', to=settings.AUTH_USER_MODEL, verbose_name='участники'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('ok', 'Пришёл, всё хорошо'), ('no_show', 'Не пришёл')], max_length=16, verbose_name='оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('gathering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='gatherings.gathering')),
                ('ratee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL, verbose_name='кого оценили')),
                ('rater', models.ForeignKey(db_comment='никогда не отдаётся оцениваемому', on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL, verbose_name='кто оценил')),
            ],
            options={
                'verbose_name': 'оценка',
                'verbose_name_plural': 'оценки',
                'db_table_comment': 'Оценки участников после встречи: ok / no_show',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_at', models.DateTimeField(auto_now_add=True, verbose_name='отмечено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
                ('gathering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='gatherings.gathering')),
            ],
            options={
                'verbose_name': 'отметка «Я пришёл»',
                'verbose_name_plural': 'отметки «Я пришёл»',
                'db_table_comment': 'Отметки «Я пришёл»; сбор состоялся, если их >= 2',
                'constraints': [models.UniqueConstraint(fields=('gathering', 'user'), name='attendance_once')],
            },
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(condition=models.Q(('left_at__isnull', True)), fields=('gathering', 'user'), name='participation_one_active'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_creator', True), ('left_at__isnull', True)), fields=('gathering',), name='participation_one_creator'),
        ),
        migrations.AddIndex(
            model_name='gathering',
            index=models.Index(condition=models.Q(('moderation_status', 'published'), ('status', 'open')), fields=['starts_at'], name='gathering_feed'),
        ),
        migrations.AddIndex(
            model_name='gathering',
            index=models.Index(fields=['creator', 'status'], name='gathering_creator_status'),
        ),
        migrations.AddConstraint(
            model_name='gathering',
            constraint=models.CheckConstraint(condition=models.Q(('seats__gte', 3), ('seats__lte', 6)), name='gathering_seats_3_6'),
        ),
        migrations.AddConstraint(
            model_name='gathering',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'cancelled'), _negated=True), ('cancelled_at__isnull', False), _connector='OR'), name='gathering_cancelled_has_date'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('gathering', 'rater', 'ratee'), name='rating_once_per_pair'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(condition=models.Q(('rater', models.F('ratee')), _negated=True), name='rating_not_self'),
        ),
    ]
