# Generated by Django 5.2.17 on 2026-10-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gathering',
            name='after_prompt_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='«Как прошла встреча?» отправлено'),
        ),
        migrations.AddField(
            model_name='gathering',
            name='happened',
            field=models.BooleanField(blank=True, db_comment='итог через 12 ч после начала: >= 2 отметок «Я пришёл»; NULL — ещё не подведён', null=True, verbose_name='состоялся'),
        ),
        migrations.AddField(
            model_name='gathering',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='напоминание отправлено'),
        ),
        migrations.AddField(
            model_name='gathering',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='итог подведён'),
        ),
    ]
