# Generated by Django 5.2.17 on 2026-10-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherings', '0002_task_markers'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='source',
            field=models.CharField(choices=[('feed', 'Лента'), ('for_you', 'Для тебя'), ('map', 'Карта'), ('link', 'Ссылка / другое')], db_comment='для метрики ТЗ: конверсия «Для тебя» -> «Я пришёл» против ленты', default='link', max_length=16, verbose_name='откуда пришёл'),
        ),
    ]
