# Generated by Django 5.2.17 on 2026-10-05 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('gatherings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_comment='в нижнем регистре', max_length=100, unique=True, verbose_name='слово')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='добавлено')),
            ],
            options={
                'verbose_name': 'запрещённое слово',
                'verbose_name_plural': 'запрещённые слова',
                'db_table_comment': 'Список запрещённых слов: совпадение -> сбор на проверку',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('user', 'Пользователь'), ('gathering', 'Сбор'), ('message', 'Сообщение')], max_length=16, verbose_name='на что')),
                ('reason', models.CharField(choices=[('spam', 'Спам или реклама'), ('harassment', 'Оскорбления, травля'), ('inappropriate', 'Неприемлемый контент'), ('danger', 'Угроза безопасности'), ('underage', 'Похоже, младше 18'), ('fake', 'Фейковый профиль'), ('no_show', 'Не пришёл, не предупредил'), ('other', 'Другое')], max_length=32, verbose_name='причина')),
                ('text', models.CharField(blank=True, max_length=1000, verbose_name='комментарий')),
                ('priority', models.CharField(choices=[('critical', 'Критичная'), ('high', 'Высокая'), ('normal', 'Обычная')], db_comment='critical сразу дублируется в Telegram-чат модераторов', default='normal', max_length=16, verbose_name='приоритет')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_review', 'В работе'), ('resolved', 'Принято решение'), ('rejected', 'Отклонена')], default='new', max_length=16, verbose_name='статус')),
                ('resolution_note', models.TextField(blank=True, verbose_name='решение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='закрыта')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_assigned', to=settings.AUTH_USER_MODEL, verbose_name='модератор')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_sent', to=settings.AUTH_USER_MODEL, verbose_name='автор жалобы')),
                ('target_gathering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='gatherings.gathering')),
                ('target_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='chat.message')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'жалоба',
                'verbose_name_plural': 'жалобы',
                'db_table_comment': 'Жалобы на пользователей, сборы и сообщения',
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('hide_message', 'Скрыл сообщение'), ('hide_gathering', 'Скрыл сбор'), ('publish_gathering', 'Опубликовал сбор после проверки'), ('warn', 'Предупредил'), ('pause', 'Пауза 7 дней'), ('ban', 'Заблокировал'), ('revoke_sanction', 'Снял санкцию'), ('resolve_report', 'Закрыл жалобу'), ('reject_report', 'Отклонил жалобу'), ('change_role', 'Изменил роль')], max_length=32, verbose_name='действие')),
                ('target_type', models.CharField(db_comment='user / gathering / message / report', max_length=32, verbose_name='тип объекта')),
                ('target_id', models.BigIntegerField(verbose_name='id объекта')),
                ('reason', models.TextField(db_comment='обязательна для любого действия', verbose_name='причина')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='когда')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_actions', to=settings.AUTH_USER_MODEL, verbose_name='модератор')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='log_entries', to='moderation.report', verbose_name='по жалобе')),
            ],
            options={
                'verbose_name': 'запись журнала модерации',
                'verbose_name_plural': 'журнал модерации',
                'db_table_comment': 'Неизменяемый журнал модераторов: UPDATE/DELETE запрещены триггером',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('warning', 'Предупреждение'), ('pause', 'Пауза'), ('ban', 'Блокировка')], max_length=16, verbose_name='тип')),
                ('reason', models.TextField(verbose_name='причина')),
                ('ends_at', models.DateTimeField(blank=True, db_comment='пауза — +7 дней; бан — NULL (бессрочно)', null=True, verbose_name='действует до')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='снята досрочно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='назначена')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanctions_given', to=settings.AUTH_USER_MODEL, verbose_name='модератор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'санкция',
                'verbose_name_plural': 'санкции',
                'db_table_comment': 'Санкции модераторов: warning / pause / ban',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL, verbose_name='кого')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to=settings.AUTH_USER_MODEL, verbose_name='кто заблокировал')),
            ],
            options={
                'verbose_name': 'блокировка',
                'verbose_name_plural': 'блокировки',
                'db_table_comment': 'Блокировки между пользователями (действуют в обе стороны)',
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='block_once'), models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='block_not_self')],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(condition=models.Q(('status__in', ['new', 'in_review'])), fields=['priority', 'created_at'], name='report_queue'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_gathering__isnull', True), ('target_message__isnull', True), ('target_type', 'user'), ('target_user__isnull', False)), models.Q(('target_gathering__isnull', False), ('target_message__isnull', True), ('target_type', 'gathering'), ('target_user__isnull', True)), models.Q(('target_gathering__isnull', True), ('target_message__isnull', False), ('target_type', 'message'), ('target_user__isnull', True)), _connector='OR'), name='report_exactly_one_target'),
        ),
        migrations.AddIndex(
            model_name='moderationlog',
            index=models.Index(fields=['target_type', 'target_id'], name='modlog_target'),
        ),
        migrations.AddConstraint(
            model_name='moderationlog',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='modlog_reason_required'),
        ),
        migrations.AddConstraint(
            model_name='usersanction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'pause'), _negated=True), ('ends_at__isnull', False), _connector='OR'), name='sanction_pause_has_end'),
        ),
    ]
