# Generated by Django 5.2.17 on 2026-10-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('emoji', models.CharField(blank=True, max_length=8, verbose_name='эмодзи')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'db_table_comment': 'Категории сборов: кино, прогулка, настолки...',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
            ],
            options={
                'verbose_name': 'интерес',
                'verbose_name_plural': 'интересы',
                'db_table_comment': 'Интересы для профиля и будущего подбора «Для тебя»',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
