# Generated by Django 5.2.17 on 2026-10-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Какие сборы подходят людям с этим интересом — для подбора «Для тебя»', related_name='interests', to='catalog.category', verbose_name='категории сборов'),
        ),
    ]
