# Generated by Django 5.2.17 on 2026-10-05 11:21

import apps.accounts.managers
import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(db_comment='+7XXXXXXXXXX, идентификатор входа', max_length=16, unique=True, verbose_name='телефон')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='имя')),
                ('photo', models.ImageField(blank=True, upload_to=apps.accounts.models.avatar_upload_to, verbose_name='фото')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', max_length=16, verbose_name='роль')),
                ('adult_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='подтвердил 18+')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='согласие с правилами и обработкой данных')),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='онбординг завершён')),
                ('reliability', models.FloatField(blank=True, db_comment='0..1 по последним 10 сборам; NULL — пока нет истории. Формула: docs/adr/0001', null=True, verbose_name='надёжность')),
                ('happened_gatherings_count', models.PositiveIntegerField(db_comment='сборы, где пользователь отметил «Я пришёл»', default=0, verbose_name='состоявшихся сборов')),
                ('is_staff', models.BooleanField(default=False, verbose_name='доступ в админку')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='зарегистрирован')),
                ('deleted_at', models.DateTimeField(blank=True, db_comment='мягкое удаление через DELETE /me', null=True, verbose_name='удалён')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('interests', models.ManyToManyField(blank=True, related_name='users', to='catalog.interest', verbose_name='интересы')),
                ('university', models.ForeignKey(blank=True, db_comment='по желанию, без подтверждения; ничего не ограничивает', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='universities.university', verbose_name='вуз')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'db_table_comment': 'Пользователи KUN: вход по телефону, профиль',
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=16, verbose_name='телефон')),
                ('code_hash', models.CharField(db_comment='сам код не храним, только хэш', max_length=128, verbose_name='хэш кода')),
                ('expires_at', models.DateTimeField(verbose_name='действует до')),
                ('attempts', models.PositiveSmallIntegerField(db_comment='5 неверных -> locked_until', default=0, verbose_name='неверных вводов')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='заблокирован до')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='использован')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP запроса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
            ],
            options={
                'verbose_name': 'код входа',
                'verbose_name_plural': 'коды входа',
                'db_table_comment': 'Коды входа по SMS (хэши), попытки и блокировки',
                'indexes': [models.Index(fields=['phone', '-created_at'], name='authcode_phone_recent')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='ключ сессии')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='браузер/устройство')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='последняя активность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'сессия',
                'verbose_name_plural': 'сессии',
                'db_table_comment': 'Сессии пользователя (ключ из django_session) — для выхода со всех устройств',
            },
        ),
    ]
