# Generated by Django 5.2.17 on 2026-10-05 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gatherings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('user', 'Сообщение участника'), ('system', 'Системное')], default='user', max_length=16, verbose_name='тип')),
                ('system_event', models.CharField(blank=True, choices=[('joined', 'Присоединился'), ('left', 'Вышел'), ('updated', 'Сбор изменён'), ('cancelled', 'Сбор отменён'), ('creator_changed', 'Сменился создатель')], max_length=32, verbose_name='событие')),
                ('text', models.CharField(blank=True, db_comment='в логи не пишется', max_length=1000, verbose_name='текст')),
                ('payload', models.JSONField(blank=True, db_comment='для системных: кто, что изменилось', default=dict, verbose_name='данные события')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='скрыто модератором')),
                ('hidden_at', models.DateTimeField(blank=True, null=True, verbose_name='скрыто')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='отправлено')),
                ('author', models.ForeignKey(blank=True, db_comment='NULL у системных сообщений', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('gathering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='gatherings.gathering')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'db_table_comment': 'Чат сбора: сообщения участников и системные события',
                'indexes': [models.Index(fields=['gathering', '-created_at'], name='message_history')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('kind', 'system'), ('system_event__gt', '')), models.Q(('kind', 'user'), ('system_event', '')), _connector='OR'), name='message_system_event_matches_kind')],
            },
        ),
    ]
